fml

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -8,6 +8,10 @@ jobs:
       - image: ubuntu:xenial-20170410
     steps:
       - run:
+          #dtests fail to start C* when run as root
+          name: Make the stupid fucking user
+          command: useradd -m fml
+      - run:
           name: apt-get install packages
           command: |
             echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
@@ -38,6 +42,7 @@ jobs:
       - run:
           name: Clone git repos
           command: |
+            su fml && cd
             git clone --single-branch --depth 1 https://github.com/riptano/cassandra-dtest ~/cassandra-dtest
             git clone --single-branch --depth 1 --branch $CIRCLE_BRANCH git://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git ~/cassandra
 #      - run:
@@ -60,6 +65,7 @@ jobs:
       - run:
           name: Configure virtualenv and python dependencies
           command: |
+            su fml && cd
             virtualenv --python=python2 --no-site-packages venv
             source venv/bin/activate
             export CASS_DRIVER_NO_EXTENSIONS=true
@@ -69,6 +75,7 @@ jobs:
       - run:
           name: Build Cassandra
           command: |
+            su fml && cd
             cd ~/cassandra
             # Loop to prevent failure due to maven-ant-tasks not downloading a jar..
             for x in $(seq 1 3); do
@@ -89,6 +96,7 @@ jobs:
           no_output_timeout: 10m
           command: |
             #"$HOME/cassandra-dtest/**/*.py"
+            su fml && cd
             echo `circleci tests glob "$HOME/cassandra/test/unit/**" "$HOME/cassandra-dtest/**/*.py" | grep -v upgrade_tests | grep -v "cassandra-thrift" | grep -v "thrift_bindings" | grep -v "tools" | grep -v "dtest.py" | grep -v "$HOME/cassandra-dtest/bin" | grep -v "plugins" | circleci tests split --split-by=timings --timings-type=filename` > /tmp/tests.txt
             echo "***processed tests***"
             cat /tmp/tests.txt | sed -e 's/\s\+/\n/g' > /tmp/processed_tests.txt
@@ -105,16 +113,18 @@ jobs:
             echo "***final python tests***"
             cat /tmp/python_tests.txt | tr '\n' ' ' > /tmp/python_tests_final.txt
             cat /tmp/python_tests_final.txt
-      - run:
-         name: Run unit tests
-         command: |
-            cd ~/cassandra 
-            ant testclasslist -Dtest.classlistfile=/tmp/java_tests_final.txt || true
-         no_output_timeout: 15m
+#      - run:
+#         name: Run unit tests
+#         command: |
+#            su fml && cd
+#            cd ~/cassandra 
+#            ant testclasslist -Dtest.classlistfile=/tmp/java_tests_final.txt || true
+#         no_output_timeout: 15m
       - run:
           name: Run dtests
           no_output_timeout: 70m
           command: |
+            su fml && cd
             source venv/bin/activate
             cd ~/cassandra-dtest
             mkdir -p /tmp/dtest
@@ -130,6 +140,7 @@ jobs:
       - run:
           name: Collect and merge test results
           command: |
+            su fml && cd
             rm -f $HOME/cassandra-dtest/logs/last || true
             mkdir -p /tmp/results/junit || true
             junit-merge ~/cassandra/build/test/output/*.xml ~/cassandra-dtest/nosetests.xml || true
@@ -138,14 +149,14 @@ jobs:
       - store_test_results:
           path: /tmp/results
       - store_artifacts:
-          path: ~/cassandra/build/test/output
+          path: /home/fml/cassandra/build/test/output
           destination: junitxml
       - store_artifacts:
-          path: ~/cassandra/build/test/logs
+          path: /home/fml/cassandra/build/test/logs
           destination: logs
       - store_artifacts:
           path: /tmp/dtest
           destination: dtest
       - store_artifacts:
-          path: ~/cassandra-dtest/logs
+          path: /home/fml/cassandra-dtest/logs
           destination: dtest_logs
