circle hell

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -21,9 +21,7 @@ jobs:
             sudo ifconfig lo:4 127.0.0.7 up
             sudo ifconfig lo:4 127.0.0.8 up
             sudo ifconfig lo:4 127.0.0.9 up
-            echo git clone --single-branch --depth 1 https://github.com/riptano/cassandra-dtest ~/cassandra-dtest
             git clone --single-branch --depth 1 https://github.com/riptano/cassandra-dtest ~/cassandra-dtest
-            echo git clone --single-branch --depth 1 --branch $CIRCLE_BRANCH git://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git ~/cassandra
             git clone --single-branch --depth 1 --branch $CIRCLE_BRANCH git://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git ~/cassandra 
             virtualenv --python=python2 --no-site-packages venv
             source venv/bin/activate
@@ -33,7 +31,22 @@ jobs:
             pip freeze
       - run:
           name: Build Cassandra
-          command: cd ~/cassandra && ant build build-test
+          command: |
+            cd ~/cassandra
+            # Loop to prevent failure due to maven-ant-tasks not downloading a jar..
+            for x in $(seq 1 3); do
+                ant build built-test
+                RETURN="$?"
+                if [ "${RETURN}" -eq "0" ]; then
+                    break
+                fi
+            done
+            # Exit, if we didn't build successfully
+            if [ "${RETURN}" -ne "0" ]; then
+                echo "Build failed with exit code: ${RETURN}"
+                exit ${RETURN}
+            fi
+          no_output_timeout: 2h
       - run:
           name: Determine tests to run
           no_output_timeout: 2h
